name: Build Go Proxy for Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'  # Adjust to your preferred Go version

    - name: Build Windows binary
      run: |
        go build -o proxy.exe main.go

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: proxy-windows
        path: proxy.exe
